import * as fs from "node:fs";
import * as path from "node:path";
import type { ProgressEntry } from "../types/index.js";

const PROGRESS_FILE = "progress.txt";

/**
 * Get the path to the progress file in the current working directory
 */
export function getProgressPath(cwd: string = process.cwd()): string {
  return path.join(cwd, PROGRESS_FILE);
}

/**
 * Check if progress file exists
 */
export function progressExists(cwd: string = process.cwd()): boolean {
  return fs.existsSync(getProgressPath(cwd));
}

/**
 * Read the progress file content
 */
export function readProgress(cwd: string = process.cwd()): string {
  const progressPath = getProgressPath(cwd);
  if (!fs.existsSync(progressPath)) {
    return "";
  }
  return fs.readFileSync(progressPath, "utf-8");
}

/**
 * Initialize a new progress file
 */
export function initProgress(
  cwd: string = process.cwd(),
  taskFile?: string
): void {
  const progressPath = getProgressPath(cwd);
  const timestamp = new Date().toISOString();

  const content = `# Progress Log
# Generated by notion-code
# Started: ${timestamp}
${taskFile ? `# Task file: ${taskFile}` : ""}

---

`;

  fs.writeFileSync(progressPath, content, "utf-8");
}

/**
 * Append an entry to the progress file
 */
export function appendProgress(
  entry: ProgressEntry,
  cwd: string = process.cwd()
): void {
  const progressPath = getProgressPath(cwd);

  // Initialize if doesn't exist
  if (!fs.existsSync(progressPath)) {
    initProgress(cwd);
  }

  const entryText = `
## Iteration ${entry.iteration} - ${entry.timestamp}
**Task:** ${entry.taskTitle} (${entry.taskId})
**Action:** ${entry.action}
${entry.notes ? `**Notes:** ${entry.notes}` : ""}

---
`;

  fs.appendFileSync(progressPath, entryText, "utf-8");
}

/**
 * Mark the progress file as complete
 */
export function markProgressComplete(cwd: string = process.cwd()): void {
  const progressPath = getProgressPath(cwd);

  if (!fs.existsSync(progressPath)) {
    return;
  }

  const timestamp = new Date().toISOString();
  const completion = `
# ==========================================
# ALL TASKS COMPLETE
# Finished: ${timestamp}
# ==========================================
`;

  fs.appendFileSync(progressPath, completion, "utf-8");
}

/**
 * Delete the progress file (cleanup after sprint)
 */
export function deleteProgress(cwd: string = process.cwd()): void {
  const progressPath = getProgressPath(cwd);
  if (fs.existsSync(progressPath)) {
    fs.unlinkSync(progressPath);
  }
}

/**
 * Get the current iteration number from the progress file
 */
export function getCurrentIteration(cwd: string = process.cwd()): number {
  const content = readProgress(cwd);
  const matches = content.match(/## Iteration (\d+)/g);
  if (!matches) {
    return 0;
  }
  return matches.length;
}
